name: R4B-Release IVA Config

on:
  push:
    paths:
      - "IVA-Configs/**"

jobs:
  # Job 1 : IVA Config Auto Tagging
  Config-AutoTagging:
    name: Config-AutoTag – ${{ github.ref_name }}
    environment: ${{ vars.DefultEnvironment }}
    #self-hosted runner
    runs-on:
      - ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Next Tag
        id: tag
        run: |
          RAW_BRANCH_NAME="${GITHUB_REF##*/}"
          SAFE_BRANCH_NAME=$(echo "$RAW_BRANCH_NAME" | tr '/' '-')

          PREFIX="IVA-Config-${SAFE_BRANCH_NAME}"
          LAST_TAG=$(git tag --list "${PREFIX}-v*" | sort -V | tail -n 1)

          if [ -z "$LAST_TAG" ]; then
            NEXT_VERSION="${PREFIX}-v1"
          else
            VERSION_NUM=$(echo "$LAST_TAG" | grep -oE '[0-9]+$')
            NEXT_VERSION="${PREFIX}-v$((VERSION_NUM + 1))"
          fi

          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
          echo "🏷 Next Tag: $NEXT_VERSION"

      - name: Push Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git tag ${{ steps.tag.outputs.version }}
          git push origin ${{ steps.tag.outputs.version }}

          echo "🏷 Tag pushed: ${{ steps.tag.outputs.version }}"
